apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-deployment
  labels:
    app: scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      volumes:
      - name: scanner-storage
        persistentVolumeClaim:
          claimName: scanner-claim
      containers:
      - name: nmap
        image: instrumentisto/nmap
        volumeMounts:
        - mountPath: "/nmap"
          name: scanner-storage
        command: ["nmap"]
        args: ["-Pn","-sS","-iL","/nmap/targets.txt","-oN","/nmap/results/%d-%m-%Y"]
