apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-deployment
  labels:
    app: scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      volumes:
      - name: scanner-storage
        persistentVolumeClaim:
          claimName: scanner-claim
      containers:
      - name: nmap
        image: instrumentisto/nmap
        volumeMounts:
        - mountPath: "/data"
          name: scanner-storage
        command: ["nmap"]
        args: ["-Pn","-sS","192.168.1.49","-oN","/data/example.txt"]
